// SPDX-License-Identifier: Apache-2.0
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Generated by: python3 csv2bin.py sc_utf8.csv sc_utf8.h -f hex
#include "../sc_utf8.h"

#define LINE_NAME_MAX 40
#define STATION_NAME_MAX 40
#define RECORD_SIZE (3 + LINE_NAME_MAX + STATION_NAME_MAX)

static size_t decode_string(const unsigned char *p, size_t max_len, char *out, size_t out_size) {
    size_t len = 0;
    while (len < max_len && p[len] != 0) {
        ++len;
    }
    if (out_size == 0) {
        return len;
    }
    if (len >= out_size) {
        len = out_size - 1;
    }
    memcpy(out, p, len);
    out[len] = '\0';
    return len;
}

static int find_station(int area, int line, int station,
                        char *line_name, size_t line_size,
                        char *station_name, size_t station_size) {
    size_t off;
    for (off = 0; off + RECORD_SIZE <= sc_utf8_len; off += RECORD_SIZE) {
        const unsigned char *rec = sc_utf8 + off;
        if (rec[0] != (unsigned char)area) {
            continue;
        }
        if (rec[1] != (unsigned char)line) {
            continue;
        }
        if (rec[2] != (unsigned char)station) {
            continue;
        }

        decode_string(rec + 3, LINE_NAME_MAX, line_name, line_size);
        decode_string(rec + 3 + LINE_NAME_MAX, STATION_NAME_MAX, station_name, station_size);
        return 1;
    }
    return 0;
}

static void print_usage_jp(const char *prog) {
    printf("使い方:\n");
    printf("  %s                 全駅を表示\n", prog);
    printf("  %s エリア           指定エリアの駅を表示\n", prog);
    printf("  %s エリア 路線      指定エリア・路線の駅を表示\n", prog);
    printf("  %s エリア 路線 駅   指定した駅を表示\n", prog);
    printf("\n");
    printf("例:\n");
    printf("  %s 0\n", prog);
    printf("  %s 0 239\n", prog);
    printf("  %s 0 239 20\n", prog);
    printf("\n");
    printf("備考:\n");
    printf("  データは sc_utf8.h の配列から読み取ります。\n");
}

int main(int argc, char **argv) {
    if (argc == 2 && (strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0)) {
        print_usage_jp(argv[0]);
        return 0;
    }

    if (sc_utf8_len % RECORD_SIZE != 0) {
        fprintf(stderr, "sc_utf8_len (%u) is not a multiple of record size (%u)\n",
                sc_utf8_len, (unsigned int)RECORD_SIZE);
        return 1;
    }

    if (argc == 4) {
        int area = atoi(argv[1]);
        int line = atoi(argv[2]);
        int station = atoi(argv[3]);

        if (area < 0 || area > 255 || line < 0 || line > 255 || station < 0 || station > 255) {
            fprintf(stderr, "range error: 0-255 の範囲で指定してください\n");
            return 1;
        }

        char line_name[LINE_NAME_MAX + 1];
        char station_name[STATION_NAME_MAX + 1];
        if (find_station(area, line, station, line_name, sizeof(line_name),
                         station_name, sizeof(station_name))) {
            printf("%d %d %d %s %s\n", area, line, station, line_name, station_name);
            return 0;
        }

        fprintf(stderr, "not found: %d %d %d\n", area, line, station);
        return 1;
    }

    if (argc == 3) {
        int area = atoi(argv[1]);
        int line = atoi(argv[2]);
        if (area < 0 || area > 255 || line < 0 || line > 255) {
            fprintf(stderr, "range error: 0-255 の範囲で指定してください\n");
            return 1;
        }

        size_t off;
        for (off = 0; off + RECORD_SIZE <= sc_utf8_len; off += RECORD_SIZE) {
            const unsigned char *rec = sc_utf8 + off;
            if (rec[0] != (unsigned char)area || rec[1] != (unsigned char)line) {
                continue;
            }
            int station = rec[2];
            char line_name[LINE_NAME_MAX + 1];
            char station_name[STATION_NAME_MAX + 1];
            decode_string(rec + 3, LINE_NAME_MAX, line_name, sizeof(line_name));
            decode_string(rec + 3 + LINE_NAME_MAX, STATION_NAME_MAX,
                          station_name, sizeof(station_name));
            printf("%d %d %d %s %s\n", area, line, station, line_name, station_name);
        }
        return 0;
    }

    if (argc == 2) {
        int area = atoi(argv[1]);
        if (area < 0 || area > 255) {
            fprintf(stderr, "range error: 0-255 の範囲で指定してください\n");
            return 1;
        }

        size_t off;
        for (off = 0; off + RECORD_SIZE <= sc_utf8_len; off += RECORD_SIZE) {
            const unsigned char *rec = sc_utf8 + off;
            if (rec[0] != (unsigned char)area) {
                continue;
            }
            int line = rec[1];
            int station = rec[2];
            char line_name[LINE_NAME_MAX + 1];
            char station_name[STATION_NAME_MAX + 1];
            decode_string(rec + 3, LINE_NAME_MAX, line_name, sizeof(line_name));
            decode_string(rec + 3 + LINE_NAME_MAX, STATION_NAME_MAX,
                          station_name, sizeof(station_name));
            printf("%d %d %d %s %s\n", area, line, station, line_name, station_name);
        }
        return 0;
    }

    if (argc != 1) {
        print_usage_jp(argv[0]);
        return 1;
    }

    {
        size_t off;
        for (off = 0; off + RECORD_SIZE <= sc_utf8_len; off += RECORD_SIZE) {
            const unsigned char *rec = sc_utf8 + off;
            int area = rec[0];
            int line = rec[1];
            int station = rec[2];
            char line_name[LINE_NAME_MAX + 1];
            char station_name[STATION_NAME_MAX + 1];
            decode_string(rec + 3, LINE_NAME_MAX, line_name, sizeof(line_name));
            decode_string(rec + 3 + LINE_NAME_MAX, STATION_NAME_MAX,
                          station_name, sizeof(station_name));
            printf("%d %d %d %s %s\n", area, line, station, line_name, station_name);
        }
    }

    return 0;
}
